eureka:
   instance:
    hostname: localhost
   client:
      fetchRegistry: false
      registerWithEureka: false
      serviceUrl:
        defaultZone: ${EUREKA_SERVER_ADDRESS:http://localhost:8761}/eureka/
server:
  port: 8761